# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsxlx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='som',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
