# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsxlx', '0003_auto_20160825_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='som',
            field=models.CharField(max_length=200),
        ),
    ]
